# Viktar Siarheichyk <veq@fedoraproject.org>, 2018. #zanata
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2019-10-23 18:41+0200\n"
"PO-Revision-Date: 2018-09-06 10:33-0400\n"
"Last-Translator: Viktar Siarheichyk <veq@fedoraproject.org>\n"
"Language-Team: Belarusian\n"
"Language: be\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=3; plural=(n%10==1 && n%100!=11 ? 0 : n%10>=2 && n"
"%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2)\n"
"X-Generator: Zanata 4.6.2\n"

#: ../meh/handler.py:195
msgid ""
"Use 'continue' command to quit the debugger and get back to the main menu"
msgstr ""
"Каб выйсці з  адладчыка і вярнуцца ў галоўнае меню, можна ўжыць каманду "
"'continue'"

#: ../meh/handler.py:211
msgid "Exit the shell to get back to the main menu"
msgstr "Выйсці з абалонкі і вярнуцца ў галоўнае меню"

#. short (one-char) answer meaning "yes"
#: ../meh/ui/text.py:75
msgid "y"
msgstr "т"

#. short (one-char) answer meaning "no"
#: ../meh/ui/text.py:78
msgid "n"
msgstr "н"

#: ../meh/ui/text.py:145
msgid "Save exception"
msgstr "Захаваць выключэнне"

#: ../meh/ui/text.py:158 tmp/exception-dialog.glade.h:1
msgid "An unknown error has occurred"
msgstr "Адбылася невядомая памылка"

#: ../meh/ui/text.py:161
msgid "Report Bug"
msgstr "Паведаміць аб праблеме"

#: ../meh/ui/text.py:162
msgid "Run shell"
msgstr "Запусціць абалонку"

#: ../meh/ui/text.py:163
msgid "Quit"
msgstr "Скончыць"

#: ../meh/ui/text.py:168
msgid "Debug"
msgstr "Адладка"

#: ../meh/ui/text.py:173
msgid "What do you want to do now?"
msgstr "Што цяпер зрабіць?"

#: ../meh/ui/text.py:181
msgid "Please make your choice from above: "
msgstr "Выберыце адно з пададзеных вышэй:"

#: ../meh/ui/text.py:199
msgid "Hit ENTER to continue"
msgstr "Каб ісці далей, націсніце ENTER"

#: ../meh/ui/text.py:213
#, python-format
msgid "Are you sure you want to exit? [%(yes)s/%(no)s]"
msgstr "Сапраўды скончыць? [%(yes)s/%(no)s]"

#: ../meh/ui/gui.py:176
msgid "_Exit"
msgstr "_Закончыць"

#: tmp/exception-dialog.glade.h:2
msgid ""
"This program has encountered an unknown error. You may\n"
"report the bug below or quit the program."
msgstr ""
"У праграме здарылася невядомая памылка. Ніжэй\n"
"можна паведаміць аб праблеме альбо скончыць праграму."

#: tmp/exception-dialog.glade.h:4
msgid "_Report Bug"
msgstr "Паведаміць аб _праблеме"

#: tmp/exception-dialog.glade.h:5
msgid "_Quit"
msgstr "_Выйсці"

#: tmp/exception-dialog.glade.h:6
msgid "The output below may help determine the cause of the error:"
msgstr "Інфармацыя ніжэй можа дапамагчы вызначыць прычыну памылкі:"

#: tmp/exception-dialog.glade.h:7
msgid "'Debug' may take you to tty1."
msgstr "Выберыце 'Адладка' каб трапіць у tty1."

#: tmp/exception-dialog.glade.h:8
msgid "_Debug"
msgstr "А_дладка"

#: tmp/exception-dialog.glade.h:9
msgid "More _info..."
msgstr "Болей _інфармацыі..."

#: tmp/exception-dialog.glade.h:10
msgid "No additional info available."
msgstr "Няма болей інфармацыі."
